services:
  frontend:
    build:
      context: ../..
      dockerfile: apps/front-end/Dockerfile
    container_name: teddy-frontend
    restart: unless-stopped
    ports:
      - '${FRONTEND_PORT:-80}:80'
    environment:
      - API_URL=${API_URL:-http://localhost:3000/api}
    networks:
      - teddy-network

networks:
  teddy-network:
    driver: bridge
